theme = "showfolio"
languageCode = "en-us"
baseurl = "https://nppi3enz.github.io"
title = "NPPiProfile"


[params]
  name = "Showfolio Theme"
  description = "Modern portfolio theme for your Hugo site."
  author = "Nipitpon Chantada"
  authorEmail = "nipitpon.ch@hotmail.com"
  authorImage = "/img/pic.jpg"
  autoDarkMode = true

  copyright = "Copyright © 2021 - NPPi3enz · All rights reserved"
  favicon = "favicon.ico"

[params.homepage]
  title = "Nipitpon Chantada"
  tagline = "Full Stack Developer"
  description = "I’m working in Bangkok for finding technology-related big project management experiences and being a skillful developer."
  contact = "https://www.linkedin.com/in/nppi3enz/"

[params.homepage.codepen]
  username = "apvarun"
  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Product Development"]

[[params.homepage.resume.work]]
  name = "Ascend Commerce Co, Ltd."
  role = "PHP Developer"
  duration = "November 2018 - Present"
  description = "Develop a point-of-sale system for usage in restaurants and retail stores. We created both the front-end to integrate the web portal and the back-end to connect to mobile applications."

[[params.homepage.resume.work]]
  name = "Dfusion Co, Ltd."
  role = "Developer"
  duration = "August 2017 - October 2018"
  description = "I am a front-end and back-end developer. Not only creating websites or minisite to serve marketing campaigns, such as photo booths or ticketing system but also be part of business development such as B2B affiliate system and lead evaluator system. I have worked with big-name companies like TOYOTA, BMW, Lin sugar, Swatch."

[[params.homepage.resume.work]]
  name = "SHIPPOP Co, Ltd."
  role = "Web Developer"
  duration = "July 2016 - July 2017"
  description = "I have developed both front-end and back-end systems. To make the user more comfortable connecting with new carriers."

[[params.homepage.resume.work]]
  name = "DEK-D Co, Ltd."
  role = "Web Developer (Intern)"
  duration = "April 2014 - May 2014"
  description = "I am responsible for the research and development of the UI/UX of visual novel systems."

[params.homepage.social]
  twitter = ""
  linkedin = "https://linkedin.com/in/nppi3enz"
  github = "https://github.com/nppi3enz"
  medium = "https://medium.com/@nppi3enz"
  reddit = ""
  dribbble = ""

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
